SET DATABASE SQL SYNTAX ORA TRUE; 

CREATE SCHEMA VINODH
CREATE TABLE ADMIN_DETAILS (
      ADMIN_ID NUMBER,
      ADMIN_FIRST_NAME VARCHAR2(50 BYTE) NOT NULL,
      ADMIN_LAST_NAME  VARCHAR2(50 BYTE),
      ADMIN_USERNAME  VARCHAR2(50 BYTE) NOT NULL,
      ADMIN_PASSWORD  VARCHAR2(50 BYTE) NOT NULL,
      ADMIN_EMAIL  VARCHAR2(30) NOT NULL,
      ADMIN_ROLE  VARCHAR2(50 BYTE),
      APPLICATION_NAME VARCHAR2(25 BYTE),
      CONSTRAINT PK_ADMIN PRIMARY KEY (ADMIN_ID)
) 

CREATE TABLE CUSTOMER (
      CUST_ID NUMBER,
      FIRST_NAME VARCHAR2(50 BYTE),
      LAST_NAME  VARCHAR2(50 BYTE) NOT NULL,
      USER_NAME  VARCHAR2(50 BYTE) NOT NULL,
      EMAIL_ADDRESS  VARCHAR2(30) NOT NULL,
      PHONE_NUMBER  NUMBER,
      STREET  VARCHAR2(50 BYTE),
      TOWN VARCHAR2(25 BYTE),
      CITY  VARCHAR2(25 BYTE),
      ZIP_CODE  VARCHAR2(10 BYTE) NOT NULL,
      COUNTRY VARCHAR2(25 BYTE) NOT NULL,
      LAST_UPDATED_TIME DATE,
      CONSTRAINT PK_CUSTOMER PRIMARY KEY (CUST_ID)
) 

CREATE TABLE PARENTS (
		  CUST_ID      NUMBER,
		  FATHER_NAME    VARCHAR2(50 BYTE),
		  FATHER_PHONE NUMBER,
		  MOTHER_NAME  VARCHAR2(50 BYTE),
		  MOTHER_PHONE NUMBER,
		  CONSTRAINT PK_PARENTS PRIMARY KEY (CUST_ID)--,
		 -- CONSTRAINT FK_PARENTS FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER (CUST_ID)
)
	
CREATE TABLE PRODUCTS (
      PROD_ID NUMBER,
      CUST_ID NUMBER,
      PROD_NAME VARCHAR2(50) NOT NULL,
      PROD_DESC  VARCHAR2(200),
      REGULAR_PRICE  NUMBER,
      LAST_UPDATED_TIME DATE,
      CONSTRAINT PK_PRODUCT PRIMARY KEY (PROD_ID)--,
      --CONSTRAINT PRODUCTS_FK FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER (CUST_ID)
)
 
CREATE TABLE ORDERS (
      ORDER_ID NUMBER,
      CUST_ID NUMBER,
      TOTAL_PRICE  NUMBER,
      ORDER_DESC  VARCHAR2(100),
      ORDER_DATE  DATE,
      LAST_UPDATED_TIME DATE,
      CONSTRAINT ORDER_PK PRIMARY KEY (ORDER_ID)--,
	  --CONSTRAINT ORDER_FK FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER (CUST_ID)
)

CREATE TABLE ORDER_INVOICE (
      INVOICE_ID NUMBER,
      ORDER_ID NUMBER,
      DATE_RAISED DATE,
      AMOUNT_DUE  NUMBER,
      DATE_SETTLED DATE,
      DATE_CANCELLED DATE,
      LAST_UPDATED_TIME DATE,
      CONSTRAINT ORDER_INVOICE_PK PRIMARY KEY (INVOICE_ID)--,
      --CONSTRAINT ORDER_INVOICE_FK FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ORDER_ID)
)
 
CREATE TABLE ORDER_DETAIL (
      ORDER_ID NUMBER,
      PROD_ID NUMBER,
      PRICE  NUMBER,
      LAST_UPDATED_TIME DATE,
     CONSTRAINT ORDER_DETAIL_PK PRIMARY KEY (ORDER_ID,PROD_ID)--,
    --  CONSTRAINT ORDER_ID_FK FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ORDER_ID),
     -- CONSTRAINT PROD_ID_FK FOREIGN KEY (PROD_ID) REFERENCES PRODUCTS (PROD_ID) 
) 

CREATE TABLE PRODUCT_SURVEY (
      SURVEY_ID NUMBER,
      PROD_ID NUMBER,
      SURVEY_RESULT VARCHAR2(100), 
      YEAR_OF_SURVEY NUMBER,
      LAST_UPDATED_TIME DATE,
      CONSTRAINT PRODUCT_SURVEY_PK PRIMARY KEY (SURVEY_ID)--,
      --CONSTRAINT PRODUCT_SURVEY_FK FOREIGN KEY (PROD_ID) REFERENCES PRODUCTS (PROD_ID)
)
 
CREATE SEQUENCE ADMIN_ID_SEQ AS NUMBER START WITH 1 INCREMENT BY 1
CREATE SEQUENCE CUSTOMER_SEQ AS NUMBER START WITH 1 INCREMENT BY 1
CREATE SEQUENCE PRODUCT_SEQ AS NUMBER START WITH 1 INCREMENT BY 1 
CREATE SEQUENCE ORDERS_SEQ AS NUMBER START WITH 1 INCREMENT BY 1
CREATE SEQUENCE ORDER_INVOICE_SEQ AS NUMBER START WITH 1 INCREMENT BY 1 
CREATE SEQUENCE PRODUCT_SURVEY_SEQ AS NUMBER START WITH 1 INCREMENT BY 1

GRANT SELECT,UPDATE,INSERT,DELETE ON ADMIN_DETAILS TO PUBLIC
GRANT SELECT,UPDATE,INSERT,DELETE ON CUSTOMER TO PUBLIC
GRANT SELECT,UPDATE,INSERT,DELETE ON PARENTS TO PUBLIC
GRANT SELECT,UPDATE,INSERT,DELETE ON PRODUCTS TO PUBLIC
GRANT SELECT,UPDATE,INSERT,DELETE ON ORDERS TO PUBLIC
GRANT SELECT,UPDATE,INSERT,DELETE ON ORDER_INVOICE TO PUBLIC
GRANT SELECT,UPDATE,INSERT,DELETE ON ORDER_DETAIL TO PUBLIC
GRANT SELECT,UPDATE,INSERT,DELETE ON PRODUCT_SURVEY TO PUBLIC;
 