SET DATABASE SQL SYNTAX ORA TRUE; 

CREATE SCHEMA VINODH
CREATE TABLE CUSTOMER (
      CUST_ID INTEGER NOT NULL ,
      FIRST_NAME VARCHAR2(50) ,
      LAST_NAME  VARCHAR2(50) NOT NULL,
      USER_NAME  VARCHAR2(50) NOT NULL,
      EMAIL_ADDRESS  VARCHAR2(30) NOT NULL,
      PHONE_NUMBER  INTEGER,
      STREET  VARCHAR2(50),
      TOWN VARCHAR2(25),
      CITY  VARCHAR2(25),
      ZIP_CODE  VARCHAR2(10) NOT NULL,
      COUNTRY VARCHAR2(25) NOT NULL,
      LAST_UPDATED_TIME TIMESTAMP,
      CONSTRAINT PK_CUSTOMER PRIMARY KEY (CUST_ID)
)
CREATE SEQUENCE CUSTOMER_SEQ AS INTEGER START WITH 1 INCREMENT BY 1

CREATE TABLE PRODUCTS (
      PROD_ID INTEGER NOT NULL ,
      PROD_NAME VARCHAR2(50) NOT NULL,
      PROD_DESC  VARCHAR2(200),
      REGULAR_PRICE  DOUBLE PRECISION,
      LAST_UPDATED_TIME TIMESTAMP,
      CONSTRAINT PK_PRODUCT PRIMARY KEY (PROD_ID)
)
CREATE SEQUENCE PRODUCT_SEQ AS INTEGER START WITH 1 INCREMENT BY 1 

CREATE TABLE ORDERS (
      ORDER_ID INTEGER NOT NULL ,
      CUST_ID INTEGER NOT NULL ,
      TOTAL_PRICE  DOUBLE PRECISION,
      OREDER_DESC  VARCHAR2(100),
      ORDER_DATE  TIMESTAMP,
      LAST_UPDATED_TIME TIMESTAMP,
      CONSTRAINT ORDER_PK PRIMARY KEY (ORDER_ID),
	  CONSTRAINT ORDER_FK FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER (CUST_ID)
)
CREATE SEQUENCE ORDERS_SEQ AS INTEGER START WITH 1 INCREMENT BY 1

CREATE TABLE ORDER_DETAIL (
      ORDER_ID INTEGER NOT NULL ,
      PROD_ID INTEGER NOT NULL,
      PRICE  DOUBLE PRECISION,
      LAST_UPDATED_TIME TIMESTAMP,
      CONSTRAINT ORDER_DETAIL_PK PRIMARY KEY (ORDER_ID,PROD_ID),
      CONSTRAINT ORDER_ID_FK FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ORDER_ID),
      CONSTRAINT PROD_ID_FK FOREIGN KEY (PROD_ID) REFERENCES PRODUCTS (PROD_ID) 
)
 
CREATE TABLE ORDER_INVOICE (
      INVOICE_ID INTEGER NOT NULL ,
      ORDER_ID INTEGER NOT NULL ,
      DATE_RAISED TIMESTAMP,
      AMOUNT_DUE  DOUBLE PRECISION,
      DATE_SETTLED TIMESTAMP,
      DATE_CANCELLED TIMESTAMP,
      LAST_UPDATED_TIME TIMESTAMP,
      CONSTRAINT ORDER_INVOICE_PK PRIMARY KEY (INVOICE_ID),
      CONSTRAINT ORDER_INVOICE_FK FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ORDER_ID);
)
CREATE SEQUENCE ORDER_INVOICE_SEQ AS INTEGER START WITH 1 INCREMENT BY 1 

CREATE TABLE PRODUCT_SURVEY (
      SURVEY_ID INTEGER NOT NULL ,
      PROD_ID INTEGER NOT NULL ,
      SURVEY_RESULT VARCHAR2(100), 
      YEAR_OF_SURVEY INTEGER,
      LAST_UPDATED_TIME TIMESTAMP,
      CONSTRAINT ORDER_INVOICE_PK PRIMARY KEY (SURVEY_ID),
      CONSTRAINT ORDER_INVOICE_FK FOREIGN KEY (PROD_ID) REFERENCES ORDERS (ORDER_ID);
)
CREATE SEQUENCE PRODUCT_SURVEY_SEQ AS INTEGER START WITH 1 INCREMENT BY 1 


GRANT SELECT,UPDATE,INSERT,DELETE ON CUSTOMER TO PUBLIC
GRANT SELECT,UPDATE,INSERT,DELETE ON PRODUCTS TO PUBLIC
GRANT SELECT,UPDATE,INSERT,DELETE ON ORDERS TO PUBLIC
GRANT SELECT,UPDATE,INSERT,DELETE ON ORDER_DETAIL TO PUBLIC
GRANT SELECT,UPDATE,INSERT,DELETE ON ORDER_INVOICE TO PUBLIC
GRANT SELECT,UPDATE,INSERT,DELETE ON PRODUCT_SURVEY TO PUBLIC
GRANT SELECT,UPDATE,INSERT,DELETE ON CUSTOMER TO PUBLIC;


